services:
  # PostgreSQL database
  postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: axum_base
      POSTGRES_USER: axum_user
      POSTGRES_PASSWORD: axum_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d/migrations:ro
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U axum_user -d axum_base"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Axum application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      DATABASE_URL: postgres://axum_user:axum_password@postgres:5432/axum_base
      RUST_LOG: info
      PORT: 3093
      HOST: 0.0.0.0
      SESSION_SECRET: your-secret-key-change-this-in-production
    ports:
      - "3093:3093"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3093/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  postgres_data:
    driver: local
